### About reduce_mean 

The functionality of numpy.mean and tensorflow.reduce_mean are the *same*

In [0]:
import numpy as np
import tensorflow as tf

In [0]:
c = np.array([[3.,4], [5.,6], [6.,7]])
print(c)

[[3. 4.]
 [5. 6.]
 [6. 7.]]


In [0]:
m1 = np.mean(c, axis = 1)
print(m1)

[3.5 5.5 6.5]


In [0]:
m2 = tf.reduce_mean(c,axis = 1)
with tf.Session() as sess:
    result = sess.run(m2)
    print(result)

[3.5 5.5 6.5]
